### ISSUE TITLE
Get Transactions

### ISSUE THREAD

**Issue by benfoster** [TrueLayer/truelayer-dotnet#92]
https://pay-api-specs.t7r.dev/mvp/#tag/Merchant-Accounts/paths/~1merchant_accounts~1{id}~1transactions/get

**Comment by tl-antonio-valentini** [comment]
Link is dead :cry:

**Comment by tl-antonio-valentini** [comment]
Probably this is the right reference?
- [get account transactions](https://docs.truelayer.com/reference/getaccounttransactions)
- [get account pending transactions](https://docs.truelayer.com/reference/getaccountpendingtransactions)

**Comment by tl-antonio-valentini** [comment]
@tl-mauro-franchi
